[private]
just:
    @just --list --list-prefix="--> "

# Install dependencies
install:
    cargo build

# Format the code
format:
    cargo fmt

# Build the project
build: lint
    cargo build

# Run the test suite
test *args:
    cargo test {{args}}

# Lint the project
lint:
    cargo clippy -- -D warnings
