[private]
just:
    @just --list --unsorted --list-prefix='--> '

# Install dependencies
[group('prep')]
install:
    cargo build

# Build the project
[group('dev')]
build: lint
    cargo build

# Run the test suite
[group('dev')]
test *args:
    cargo test {{args}}

# Run the project
[group('dev')]
run:
    cargo run

# Lint the projet
[group('format')]
lint:
    cargo clippy -- -D warnings

# Format the code
[group('format')]
format:
    cargo fmt
