[private]
just:
    @just --list --list-prefix="--> "

# Install dependencies
install:
    cargo build

# Build the project
build:
    cargo build

# Run the test suite
test *args:
    cargo test {{args}}
